### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by HilariousGil** [dataoverheid/ckanext-dataoverheid#6]
With the new Release the file "list_updater.py" changed to "ckan_updater.py", it is not reflected in the Documentation.

Edit: Also it needs mandatory parameters now, otherwise it will break if not provided "--list" argument, would be nice to have it in the documentation as well.

**Comment by WterBerg** [comment]
Thanks for noticing; we've updated the installation instructions present in the README.md file in https://github.com/dataoverheid/ckanext-dataoverheid/pull/8 which will be merged into master shortly.
